ALTER TABLE barangays ADD COLUMN IF NOT EXISTS pwd INT DEFAULT 0;
ALTER TABLE barangays ADD COLUMN IF NOT EXISTS elderly INT DEFAULT 0;
ALTER TABLE barangays ADD COLUMN IF NOT EXISTS children INT DEFAULT 0;
ALTER TABLE barangays ADD COLUMN IF NOT EXISTS pregnant INT DEFAULT 0;
